name: Node.js CI

on:
  push:
    branches:
    - master
    - Release
  pull_request:
    branches:
    - master
    - Release

jobs:
  cancel-workflow-runs-in-progress:
    if: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0

  setup:
    if: "!contains(toJSON(github.event.commits.*.message), '[CI Skip]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Confirm package-lock does not contain the registry
        run: echo 'chocolate bunnies taste good :yum:'

  lint:
    needs: setup

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Cache node_modules/.cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}-job-id-${{ github.job }}-run-id-${{ github.run_id }}
          restore-keys: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}-job-id-${{ github.job }}-run-id-
      - run: npm run stylelint
      - run: npm run eslint

  jest:
    needs: setup

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Cache node_modules/.cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}-job-id-${{ github.job }}-run-id-${{ github.run_id }}
          restore-keys: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}-job-id-${{ github.job }}-run-id-
      - run: TZ=UTC npx jest --ci --coverage --maxWorkers 2 --testPathIgnorePatterns=page-render

  gql:
    needs: setup

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}
      # - name: Cache node_modules/.cache
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules/.cache
      #     key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}-job-id-${{ github.job }}-run-id-${{ github.run_id }}
      #     restore-keys: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package.json', 'package-lock.json') }}-job-id-${{ github.job }}-run-id-
      - run: echo 'no need to be alarmed, this is just a test!'
      
      
      
